export const projects = [
  {
    title: 'MAPS',
    description: "The foundation for a piece of software that predicts what restauraunts a user would like using linear regression and k-nearest neighbors.",
      image: '/images/1.jpeg',
      tags: ['Python'],
    source: 'https://gitfront.io/r/dtduong103/edf14a31b13ea9bdf011b536fcca30ad64ff1be7/MAPS/',
    visit: 'https://gitfront.io/r/dtduong103/edf14a31b13ea9bdf011b536fcca30ad64ff1be7/MAPS/',
    id: 0,
  },
  {
    title: 'This Website',
    description:"Done using a great deal of advice from senior web developers and collaboration, along with no shortage of inspiration.",
    image: '/images/0.png',
    tags: ['React', 'JavaScript', 'Node.Js'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 1,
  },
  {
    title: 'Framingham Heart Disease in Data Science',
    description: "This is a google slides presentation displaying A/B Testing used to verify the results of the Framingham Heart Disease study through code and data science principles.",
      image: '/images/CTotsqby.png',
      tags: ['Python', 'Numpy', 'mathplotlib', 'SQL fundamentals'],
    source: 'https://docs.google.com/presentation/d/1NRlvkZehrzj7yZuqnyoeEWAo1OFB3956KwoY3wrgBRY/edit?usp=sharing',
    visit: 'https://docs.google.com/presentation/d/1NRlvkZehrzj7yZuqnyoeEWAo1OFB3956KwoY3wrgBRY/edit?usp=sharing',
    id: 2,
  },
  {
    title: 'Ants vs Bees',
    description: "This code is currently a work in progress and will be updated! However, it's a game plants vs zombies styles with specialized ants attacking bees to demonstrate OOP fundamentals.",
    image: '/images/3.jpeg',
    tags: ['Python'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 3,
  },
  {
    title: 'Mancala!',
    description: "Future WIP Android app!",
    image: '/images/Manc.jpeg',
    tags: ['Kotlin'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 4,
  },
];
